name: Build and Test 🏗
run-name: ${{ github.actor }} pushed and opened a Pull Request 💻
on:
  pull_request:
    types: [review_requested, opened, reopened, synchronize]
jobs:
  setup-flutter:
    runs-on: macos-13
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup fvm 🚀
        run: curl -fsSL https://fvm.app/install.sh | bash -s -- 3.2.1
      - name: Setup fvm version 📌
        run: fvm install 3.29.2 && fvm use 3.29.2 --skip-pub-get
      - run: echo "Testing ${{ github.actor }} code 🚀"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Run linter 👀
        run: |
          fvm dart analyze
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Run formatter🔎
        run: |
          format_output=$(fvm dart format lib/)
          expected_output="Formatted 0 files (0 changed)"

          if [ "$format_output" != "$expected_output" ]; then
            echo "fvm dart format lib/ found files that needed formatting:"
            echo "$format_output"
            exit 1
          fi

          echo "fvm dart format lib/ found no formatting changes needed."
          exit 0

      - name: Run tests 🔎
        run: |
          fvm flutter test
      - run: echo "🍏 This job's status is ${{ job.status }}."