name: Run tests
run-name: Testing ${{ github.actor }} code 🚀
on:
  workflow_run:
    workflows: ["Build and Setup 🏗"]
run-tests:
    needs: setup-flutter
    workflow-run: 
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Run tests 🔎
        run: |
          fvm flutter test
      - run: echo "🍏 This job's status is ${{ job.status }}."
