name: Build and Test 🏗
run-name: ${{ github.actor }} pushed and opened a Pull Request {{ github.commit }} 💻
on:
  pull_request:
    types: [review_requested, opened, reopened, synchronize]
jobs:
  setup-flutter:
    runs-on: macos-13
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup fvm 🚀
        run: curl -fsSL https://fvm.app/install.sh | bash -s -- 3.2.1
      - name: Setup fvm version 📌
        run: fvm install 3.29.2 --skip-pub-get && fvm use 3.29.2 --skip-pub-get
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: echo "Flutter pub get!"
        run: fvm flutter pub get
      - name: Installing lcov
        run: brew install lcov
      - name: Checking code coverage
        run: fvm flutter test --coverage && lcov --remove coverage/lcov.info -o coverage/lcov.info && ./coverage_check.sh
      - name: Run linter 👀
        run: |
          fvm dart analyze --fatal-warnings --fatal-infos
      - name: Run formatter🔎
        run: |
          fvm dart format lib/ --set-exit-if-changed
      - run: echo "Testing ${{ github.actor }} code 🚀"
      - name: Run tests 🔎
        run: |
          fvm flutter test
      - run: echo "🍏 This job's status is ${{ job.status }}."